@startuml
skinparam style strictuml
skinparam defaultfontname Verdana
title RDCU pour <b>supprimerQuestionnaire (idQuestionnaire: number, idEspaceCours: number)</b>
participant ":GestionnaireQuestionnaire" as gq
participant "espaceCours:\nEspaceCours" as ec
participant ":Universite <sup>1</sup>" as u
participant "espacesCours:\nMap<number,EspaceCours>" as mec
participant "espaceCours:\nEspaceCours" as ec
participant "questionnaires:\nMap<number,Questionnaire>" as mq

->gq : supprimerQuestionnaire(idQuestionnaire: number, idEspaceCours: number)
note right : selon <b>Controleur</b> (GestionnaireQuestionnaire est \nun contrôleur de session)

gq -> u : espaceCours = getEspaceCoursParId(idEspaceCours)
note right : selon <b>Expert</b> (Universite contient \ntous les espaces cours)

u -> mec : espaceCours = get(idEspaceCours)

gq -> ec : supprimerQuestionnaire(idQuestionnaire)
note right : selon <b>Expert</b> (EspaceCours contient \nles questionnaires)

ec -> mq : delete(idQuestionnaire)

@enduml