@startuml
skinparam style strictuml
skinparam defaultfontname Verdana
title RDCU <b>recupererFichierDevoirRemis(idDevoirRemis: number, idEspaceCours: number)</b>
participant ":GestionnaireDevoir" as gd
participant ":Université<sup>1</sup>" as u
participant "espacesCours:Map<number,EspaceCours>" as mec
participant "espaceCours:EspaceCours" as ec
participant "devoirRemis:Map<number,DevoirRemis>" as md
participant "devoirRemis:DevoirRemis" as dr

->gd : pathDevoirRemis = recupererFichierDevoirRemis\n(idDevoirRemis: number, idEspaceCours: number)
note right : selon <b>Controleur</b>\n(GestionnaireDevoir\nest un contrôleur de session)

gd -> u : espaceCours = getEspaceCoursParId(idEspaceCours)
note right : selon <b>Expert</b> (Universite contient \ntous les espaces cours)\net <b>Transformer ID</b> (Universite\npossède une Map avec\nidEspaceCours comme clé)

u -> mec : espaceCours = get(idEspaceCours)

gd -> ec : devoirRemis = getDevoirRemisParId(idDevoirRemis)
note right : selon <b>Expert</b> (EspaceCours\ncontient les DevoirRemis)\net <b>Transformer ID</b> (EspaceCours\npossède une Map avec\nidDevoirRemis comme clé)

ec -> md : devoirRemis = get(idDevoirRemis)

gd -> dr : recupererFichierCorrection()
note right : selon <b>Expert</b>\n(DevoirRemis contient le\npath de son fichier\nde correction s'il y a lieu)
@enduml