@startuml
skinparam style strictuml
skinparam defaultfontname Verdana
skinparam sequence {
    MessageAlign center
}
title DSS pour <b>CU02a - Définir une évaluation (quizz, examen) dans un cours</b>\nScénario secondaire
actor ":Enseignant" as e
participant ":Système" as s
e->s : ajouterEvaluation(fréquence, dateDébut, dateFin)
s-->>e : ajoute l'évaluation au cours et affiche l'informaiton
@enduml



