@startuml
skinparam style strictuml
skinparam defaultfontname Verdana
skinparam sequence {
    MessageAlign center
}
title DSS pour <b>CU05 - Obtenir une sauvegarde moodle contenant les activtiées définies</b>\nScénario principal
actor ":Enseignant" as e
participant ":Système" as s
e->s : obtenirMBZ()
s-->>e : ouvre une boite de dialogue demandant où sauvegarder le MBZ
@enduml