@startuml
skinparam style strictuml
skinparam defaultfontname Verdana
skinparam sequence {
    MessageAlign center
}
title DSS pour <b>CU02 - Définir des activitées dans un cours</b>\nScénario principal
actor ":Enseignant" as e
participant ":Système" as s
e->s : ajouterActivité(type, fréquence, dateDébut, dateFin)
s-->>e : ajoute l'activité au cours et affiche l'informaiton
@enduml



