@startuml
skinparam style strictuml
skinparam defaultfontname Verdana
skinparam sequence {
    MessageAlign center
}
title DSS pour <b>CU01 - Obtenir l'horraire d'un cours</b>\nScénario principal
actor ":Enseignant" as e
participant ":Système" as s
e->s : fournirInformationCours(sigle: String, groupe: number, session: Enum, année: number)
s-->>e : affiche la liste des scéances à l'horraire
@enduml