import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import EventCalendar from '@/components/view/eventCalendar'
import CourseInformationForm from '@/components/view/courseInformationForm'
import {EventController} from '@/components/controller/eventController'
import ClearCalButton from '@/components/view/clearCalButton'
import {EventModel} from '@/components/model/eventModel'
import FilePickerMBZ from '@/components/view/filePickerMBZ'
import DownloadMBZButton from '@/components/view/downloadMBZButton'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <EventModel>
            <EventController>
              <EventCalendar />
              <CourseInformationForm />
              <ClearCalButton />
              <FilePickerMBZ />
              <DownloadMBZButton />
            </EventController>
          </EventModel>
        </div>
      </main>
    </>
  )
}
