import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import LocalCalendar from '@/components/view/localCalendar'
import CourseInformationForm from '@/components/view/courseInformationForm'
import {DataController} from '@/components/controller/dataController'
import ClearCalButton from '@/components/view/clearCalButton'
import {CalData} from 'src/model/calData'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <CalData>
            <DataController>
              <LocalCalendar />
              <CourseInformationForm />
              <ClearCalButton />
            </DataController>
          </CalData>
        </div>
      </main>
    </>
  )
}
