@startuml
skinparam style strictuml
skinparam defaultfontname Verdana
title RDCU pour obtenir un devoir
participant ":GestionnaireDevoir" as gd
participant "devoir:Devoir" as d

-> gd : devoir = getDevoirParId(idDevoir)
note right : selon Controleur (GestionnaireDevoir est \nun contrôleur de session)
gd->d : rechercher("idDevoir", idDevoir)
note right : selon Expert et Transformer ID

@enduml
